version: "3"

services:
  #Comp Prog Client App
  compprog-client:
    image: comp-prog-client:1.0
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true